# Generated by Django 4.2.6 on 2023-12-11 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictamenfinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('IDuser', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=80)),
                ('Oficina', models.CharField(max_length=80)),
                ('Direccion', models.CharField(max_length=80)),
                ('Tipo_Equipo', models.CharField(max_length=80)),
                ('Marca', models.CharField(max_length=80)),
                ('Modelo', models.CharField(max_length=80)),
                ('Revision', models.CharField(blank=True, choices=[('Corregido', 'Corregido'), ('Corregido 2', 'Corregido 2'), ('Corregido 3', 'Corregido 3'), ('Modifcado', 'Modificado')], max_length=80)),
                ('Revisionjefe', models.CharField(blank=True, choices=[('Pendiete', 'Pendiente'), ('Pendiente 2', 'Pendiente 2'), ('Pendiente 3', 'Pendiente 3'), ('Aprobado', 'Aprobado')], max_length=80)),
                ('Num_Serie', models.CharField(max_length=80)),
                ('Caracteristicas', models.CharField(max_length=200)),
                ('Comentario', models.CharField(blank=True, max_length=300)),
                ('Comentariojefe', models.CharField(blank=True, max_length=300)),
                ('Problema', models.TextField(max_length=1000)),
                ('Analisis', models.TextField(max_length=1000)),
                ('Proceso_Realizado', models.TextField(max_length=1000)),
                ('Dictamen_Final', models.TextField(max_length=1000)),
                ('Creacion', models.DateTimeField(auto_now_add=True, verbose_name='%Y/%m/%d')),
                ('Datecompleted', models.DateTimeField(blank=True, null=True)),
                ('Pendiente', models.BooleanField(default=False)),
                ('Imprimir', models.BooleanField(default=False)),
                ('Creado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media')),
                ('Finalizado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dictamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('IDuser', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=80)),
                ('Oficina', models.CharField(max_length=80)),
                ('Direccion', models.CharField(max_length=80)),
                ('Marca', models.CharField(max_length=80)),
                ('Modelo', models.CharField(max_length=80)),
                ('Num_Serie', models.CharField(max_length=80)),
                ('Caracteristicas', models.CharField(max_length=200)),
                ('Comentario', models.CharField(max_length=300)),
                ('Analisis', models.TextField(max_length=1000)),
                ('Dictamen_Final', models.TextField(max_length=1000)),
                ('Creacion', models.DateTimeField(auto_now_add=True)),
                ('Datecompleted', models.DateTimeField(blank=True, null=True)),
                ('Pendiente', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
