# Generated by Django 4.2.6 on 2023-10-12 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('IDuser', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=80)),
                ('Oficina', models.CharField(max_length=80)),
                ('Direccion', models.CharField(max_length=80)),
                ('Marca', models.CharField(max_length=80)),
                ('Modelo', models.CharField(max_length=80)),
                ('Num_Serie', models.CharField(max_length=80)),
                ('Caracteristicas', models.CharField(max_length=200)),
                ('Analisis', models.TextField(max_length=1000)),
                ('Dictamen_Final', models.TextField(max_length=1000)),
                ('Creacion', models.DateTimeField(auto_now_add=True)),
                ('Datecompleted', models.DateTimeField(blank=True, null=True)),
                ('Pendiente', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
