# Generated by Django 4.2.6 on 2023-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0003_dictamenfinal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamen',
            name='Comentario',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictamenfinal',
            name='Creado',
            field=models.BooleanField(default=True),
        ),
    ]
