# Generated by Django 4.2.6 on 2023-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0004_dictamen_comentario_alter_dictamenfinal_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamenfinal',
            name='Comentario',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
