# Generated by Django 4.2.6 on 2023-11-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0005_dictamenfinal_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamenfinal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/%Y/%m/%d'),
        ),
    ]
