# Generated by Django 4.2.6 on 2023-11-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0006_dictamenfinal_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamenfinal',
            name='Revision',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
