# Generated by Django 4.2.6 on 2023-11-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0007_dictamenfinal_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamenfinal',
            name='Comentariojefe',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='dictamenfinal',
            name='Comentario',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='dictamenfinal',
            name='Revision',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
