# Generated by Django 4.2.6 on 2023-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0008_dictamenfinal_comentariojefe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamenfinal',
            name='Revisionjefe',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
