# Generated by Django 4.2.6 on 2023-12-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0009_dictamenfinal_revisionjefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamenfinal',
            name='Creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='dictamenfinal',
            name='Revision',
            field=models.IntegerField(choices=[(1, 'Corregido'), (2, 'Corregido 2'), (3, 'Corregido 3')], default=1),
        ),
    ]
