# Generated by Django 4.2.6 on 2023-12-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0015_alter_dictamenfinal_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamenfinal',
            name='Revision',
            field=models.CharField(blank=True, choices=[('Corregido', 'Corregido'), ('Corregido 2', 'Corregido 2'), ('Corregido 3', 'Corregido 3'), ('Modifcado', 'Modificado')], max_length=80),
        ),
    ]
