# Generated by Django 4.2.6 on 2023-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0017_alter_dictamenfinal_revisionjefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamenfinal',
            name='Revisionjefe',
            field=models.CharField(blank=True, choices=[('Pendiete', 'Pendiente'), ('Pendiente 2', 'Pendiente 2'), ('Pendiente 3', 'Pendiente 3'), ('Aprobado', 'Aprobado')], max_length=80),
        ),
    ]
