# Generated by Django 4.2.6 on 2023-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0019_alter_dictamenfinal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamenfinal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
